version: 2
project_name: go-rcon

before:
  hooks:
    - go mod tidy

builds:
  - id: go-rcon
    main: ./cmd/cli/main.go
    binary: go-rcon
    goos:
      - linux
      - darwin # macOS
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request'
      - '^Merge branch'
